name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        # Only publish if a push (not a pull request)
        if: ${{ github.event_name == 'push' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # The PyPI API token must be stored as a GitHub secret named PYPI_API_TOKEN
          password: ${{ secrets.PYPI_API_TOKEN }}
